mode magic {
  bindsym Mod1+Escape nop
  bindsym Escape mode default

#  bindcode 24 mode default; exec --no-startup-id i3lock --color=000000
  bindcode 24 mode default; exec --no-startup-id swaylock --color=000000
  bindcode 25 split vertical
  bindcode Shift+25 split horizontal
  bindcode Mod1+25 layout toggle split
  bindcode 26 focus parent
  bindcode Mod1+26 focus child
  bindcode 27 reload
  bindcode Mod1+27 restart
  bindcode 28 layout tabbed
#  bindcode Shift+28 layout stacking
#  bindcode 29 mode default; exec --no-startup-id "cd Pictures/scrot_soon; scrot"
#  bindcode Mod1+29 mode default; exec --no-startup-id "cd Pictures/scrot_soon; sleep 0.2; scrot -f -i -scapture"
  bindcode 29 mode default; exec --no-startup-id grim -o DP-3
  bindcode Mod1+29 mode default; exec --no-startup-id slurp | grim -g -
  bindcode 30 nop
#  bindcode 31 exec --no-startup-id zutty -fg '#000' -bg '#fff' +boldColors -border 0 -showWraps -font Hack -fontsize 15
#  bindcode Mod1+31 exec --no-startup-id zutty +boldColors -border 0 -showWraps -font Hack -fontsize 15
  bindcode 31 exec --no-startup-id xterm
  bindcode 32 nop
  bindcode 33 nop

  bindcode 38 nop
  bindcode 39 nop
  bindcode 40 nop
  bindcode 41 focus mode_toggle
  bindcode Mod1+41 floating toggle
  bindcode 42 nop

  bindcode 43 focus left
  bindcode 44 focus down
  bindcode 45 focus up
  bindcode 46 focus right
  bindcode Shift+43 move left
  bindcode Shift+44 move down
  bindcode Shift+45 move up
  bindcode Shift+46 move right
  bindcode Mod1+43 workspace number 1
  bindcode Mod1+44 workspace number 2
  bindcode Mod1+45 workspace number 3
  bindcode Mod1+46 workspace number 4
  bindcode Mod1+Shift+43 move container to workspace number 1
  bindcode Mod1+Shift+44 move container to workspace number 2
  bindcode Mod1+Shift+45 move container to workspace number 3
  bindcode Mod1+Shift+46 move container to workspace number 4

  bindcode 47 nop
  bindcode Mod1+47 mode default; exec --no-startup-id SHELL=/run/current-system/sw/bin/bash dmenu_run -b -i -l 6
#  bindcode Mod1+47 mode default; exec --no-startup-id SHELL=/run/current-system/sw/bin/bash dmenu-wl_run -b -i -l 6
  bindcode Shift+47 mode default; exec --no-startup-id env PASSWORD_STORE_DIR=/home/erry/.local/share/password-store passmenu-patient --type -b -i -l 6
  bindcode Mod1+Shift+47 mode default; exec --no-startup-id env PASSWORD_STORE_DIR=/home/erry/.local/share/password-store passmenu-patient --type --wait 2 -b -i -l 6

  bindcode 52 nop
  bindcode 53 kill
  bindcode Mod1+53 exit
  bindcode 54 nop
  bindcode 55 nop
  bindcode 56 nop
  bindcode 57 nop
  bindcode 58 nop
  bindcode Mod1+58 workspace number 5
  bindcode Mod1+Shift+58 move container to workspace number 5
}
