mode magic {
  bindsym Mod1+Escape nop
  bindsym Escape mode default

  #bindcode 24 mode default; exec --no-startup-id i3lock --color=000000
  bindcode 24 mode default; exec --no-startup-id swaylock --color=000000
  bindcode 25 nop
  bindcode 26 nop
  bindcode 27 nop
  bindcode 28 nop
  bindcode 29 nop
  bindcode 30 focus parent
  bindcode Mod1+30 focus child
#  bindcode 31 exec --no-startup-id zutty -fg '#000' -bg '#fff' +boldColors -border 0 -showWraps -font Hack -fontsize 15
#  bindcode Mod1+31 exec --no-startup-id zutty +boldColors -border 0 -showWraps -font Hack -fontsize 15
  bindcode 31 exec --no-startup-id xterm fish
#  bindcode 32 mode default; exec --no-startup-id "cd Pictures/scrot_soon; scrot"
#  bindcode Mod1+32 mode default; exec --no-startup-id "cd Pictures/scrot_soon; sleep 0.2; scrot -f -i -scapture"
  bindcode 32 mode default; exec --no-startup-id grim -o DP-3
  bindcode Mod1+32 mode default; exec --no-startup-id slurp | grim -g -
  bindcode 33 mode default; exec --no-startup-id env PASSWORD_STORE_DIR=/home/erry/.local/share/password-store passmenu-patient --type -b -i -l 6
  bindcode Shift+33 mode default; exec --no-startup-id env PASSWORD_STORE_DIR=/home/erry/.local/share/password-store passmenu-patient --type --wait 2 -b -i -l 6
  bindcode Mod1+33 mode default; exec --no-startup-id SHELL=/run/current-system/sw/bin/bash dmenu_run -b -i -l 6
#  bindcode Mod1+33 mode default; exec --no-startup-id SHELL=/run/current-system/sw/bin/bash dmenu-wl_run -b -i -l 6

  bindcode 38 nop
  bindcode 39 reload
  bindcode Mod1+39 restart
  bindcode 40 nop
  bindcode 41 nop
  bindcode 42 nop
  bindcode 43 split vertical
  bindcode Shift+43 split horizontal
  bindcode Mod1+43 layout toggle split

  bindcode 44 focus left
  bindcode 45 focus down
  bindcode 46 focus up
  bindcode 47 focus right
  bindcode Shift+44 move left
  bindcode Shift+45 move down
  bindcode Shift+46 move up
  bindcode Shift+47 move right
  bindcode Mod1+44 workspace number 1
  bindcode Mod1+45 workspace number 2
  bindcode Mod1+46 workspace number 3
  bindcode Mod1+47 workspace number 4
  bindcode Mod1+48 workspace number 5
  bindcode Mod1+Shift+44 move container to workspace number 1
  bindcode Mod1+Shift+45 move container to workspace number 2
  bindcode Mod1+Shift+46 move container to workspace number 3
  bindcode Mod1+Shift+47 move container to workspace number 4
  bindcode Mod1+Shift+48 move container to workspace number 5

  bindcode 52 nop
  bindcode 53 nop
  bindcode 54 kill
  bindcode Mod1+54 exit
  bindcode 55 nop
  bindcode 56 nop
  bindcode 57 layout tabbed
  bindcode Shift+57 layout stacking
  bindcode 58 focus mode_toggle
  bindcode Mod1+58 floating toggle
}
