profile = box
profile = high-quality

hwdec = nvdec,auto
idle = yes
screenshot-directory = ~/Pictures/mpv
term-title = ${?media-title:${media-title}}${!media-title:No file} - mpv
vo = gpu-next
volume = 50

[big-cache]
profile-desc = Hold network media in memory
demuxer-max-bytes = 10GiB
keep-open = yes

[diveo]
profile-desc = ViDeo
profile = big-cache
# complement of duaio (for runtime profile selection)
audio-pitch-correction = yes
keep-open-pause = yes
pause = yes
video = auto
ytdl-format = bestvideo[width<=1280]+bestaudio/best

[duaio]
profile-desc = AuDio
profile = big-cache
# complement of diveo (for runtime profile selection)
audio-pitch-correction = no
# keep-open-pause = no # for some reason this causes mpv to use lots of cpu?
# pause = no
# not fixed yet nevermind. TODO: find out why
keep-open-pause = yes
pause = yes
video = no
ytdl-format =

[visualizer]
# mpv doesn't let me split this into multiple lines :/. this filter assumes 2
# audio channels. the colors still need to be workshopped; top is left, bottom
# is right, but the colors suggest the waveforms are swapped. this filter also
# assumes showfreqs's and showwaves's separate/split mode is vertically
# stacked, which appears to not always be true, but it works in this case. the
# specific strategy of running showfreqs and showwaves once and then rotating
# the bottom half is probably slower than rendering top and bottom halves
# separately, but i don't want to duplicate those invocations on an already
# annoyingly long config line.
lavfi-complex = [aid1] asplit=outputs=3 [ao] [waves], showfreqs=size=640x400:rate=85:mode=bar:ascale=sqrt:fscale=log:cmode=separate:colors=red|green [freqs]; [waves] showwaves=size=640x400:rate=85:mode=line:scale=lin:draw=full:split_channels=1:colors=green|red [waves]; [waves] [freqs] overlay=eval=init, split=outputs=2 [bottom], crop=out_w=in_w:out_h=in_h/2:x=0:y=0 [top]; [bottom] crop=out_w=in_w:out_h=in_h/2:x=0:y=out_h, rotate=angle=PI, [top] vstack, format=pix_fmts=yuv420p [vo]
