profile = box
profile = high-quality

idle = yes
screenshot-dir = ~/Pictures/mpv
term-title = ${?media-title:${media-title}}${!media-title:No file} - mpv
vo = gpu-next
volume = 20

[big-cache]
profile-desc = Hold network media in memory
demuxer-max-bytes = 10GiB
keep-open = yes

[diveo]
profile-desc = ViDeo
profile = big-cache
# complement of duaio (for runtime profile selection)
audio-pitch-correction = yes
pause = yes
video = auto
ytdl-format = bestvideo[width<=1920]+bestaudio/best

[duaio]
profile-desc = AuDio
profile = big-cache
# complement of diveo (for runtime profile selection)
audio-pitch-correction = no
pause = no
video = no
ytdl-format =

[vile]
profile-desc = LiVe (for streamlink)
ytdl-format = bestvideo[width<=1920]+bestaudio/best
