profile = box
profile = high-quality

hwdec
stream-lavf-o = extension_picky=0
term-title = ${?media-title:${media-title}}${!media-title:No file} - mpv
vo = gpu-next
volume = 20

[big-cache]
profile-desc = Hold media in memory
demuxer-max-bytes = 10GiB
keep-open

[diveo]
profile-desc = ViDeo
profile = big-cache
ytdl-format = bestvideo[width<=1920]+bestaudio

[duaio]
profile-desc = AuDio
profile = big-cache
no-video
ytdl-format = bestaudio

[vile]
profile-desc = LiVe
ytdl-format = bestvideo[width<=1920]+bestaudio
