tmap <M-C-@> <Esc><C-@>
tmap <M-C-A> <Esc><C-A>
tmap <M-C-B> <Esc><C-B>
tmap <M-C-C> <Esc><C-C>
tmap <M-C-D> <Esc><C-D>
tmap <M-C-E> <Esc><C-E>
tmap <M-C-F> <Esc><C-F>
tmap <M-C-G> <Esc><C-G>
tmap <M-C-H> <Esc><C-H>
tmap <M-C-I> <Esc><C-I>
tmap <M-C-J> <Esc><C-J>
tmap <M-C-K> <Esc><C-K>
tmap <M-C-L> <Esc><C-L>
tmap <M-C-M> <Esc><C-M>
tmap <M-C-N> <Esc><C-N>
tmap <M-C-O> <Esc><C-O>
tmap <M-C-P> <Esc><C-P>
tmap <M-C-Q> <Esc><C-Q>
tmap <M-C-R> <Esc><C-R>
tmap <M-C-S> <Esc><C-S>
tmap <M-C-T> <Esc><C-T>
tmap <M-C-U> <Esc><C-U>
tmap <M-C-V> <Esc><C-V>
tmap <M-C-W> <Esc><C-W>
tmap <M-C-X> <Esc><C-X>
tmap <M-C-Y> <Esc><C-Y>
tmap <M-C-Z> <Esc><C-Z>
tmap <M-C-[> <Esc><C-[>
tmap <M-C-\> <Esc><C-\>
tmap <M-C-]> <Esc><C-]>
tmap <M-C-^> <Esc><C-^>
tmap <M-C-_> <Esc><C-_>
tmap <M-Space> <Esc><Space>
tmap <M-!> <Esc>!
tmap <M-"> <Esc>"
tmap <M-#> <Esc>#
tmap <M-$> <Esc>$
tmap <M-%> <Esc>%
tmap <M-&> <Esc>&
tmap <M-'> <Esc>'
tmap <M-(> <Esc>(
tmap <M-)> <Esc>)
tmap <M-*> <Esc>*
tmap <M-+> <Esc>+
tmap <M-,> <Esc>,
tmap <M--> <Esc>-
tmap <M-.> <Esc>.
tmap <M-/> <Esc>/
tmap <M-0> <Esc>0
tmap <M-1> <Esc>1
tmap <M-2> <Esc>2
tmap <M-3> <Esc>3
tmap <M-4> <Esc>4
tmap <M-5> <Esc>5
tmap <M-6> <Esc>6
tmap <M-7> <Esc>7
tmap <M-8> <Esc>8
tmap <M-9> <Esc>9
tmap <M-:> <Esc>:
tmap <M-;> <Esc>;
tmap <M-<> <Esc><
tmap <M-=> <Esc>=
tmap <M->> <Esc>>
tmap <M-?> <Esc>?
tmap <M-@> <Esc>@
tmap <M-A> <Esc>A
tmap <M-B> <Esc>B
tmap <M-C> <Esc>C
tmap <M-D> <Esc>D
tmap <M-E> <Esc>E
tmap <M-F> <Esc>F
tmap <M-G> <Esc>G
tmap <M-H> <Esc>H
tmap <M-I> <Esc>I
tmap <M-J> <Esc>J
tmap <M-K> <Esc>K
tmap <M-L> <Esc>L
tmap <M-M> <Esc>M
tmap <M-N> <Esc>N
tmap <M-O> <Esc>O
tmap <M-P> <Esc>P
tmap <M-Q> <Esc>Q
tmap <M-R> <Esc>R
tmap <M-S> <Esc>S
tmap <M-T> <Esc>T
tmap <M-U> <Esc>U
tmap <M-V> <Esc>V
tmap <M-W> <Esc>W
tmap <M-X> <Esc>X
tmap <M-Y> <Esc>Y
tmap <M-Z> <Esc>Z
tmap <M-[> <Esc>[
tmap <M-\> <Esc>\
tmap <M-]> <Esc>]
tmap <M-^> <Esc>^
tmap <M-_> <Esc>_
tmap <M-`> <Esc>`
tmap <M-a> <Esc>a
tmap <M-b> <Esc>b
tmap <M-c> <Esc>c
tmap <M-d> <Esc>d
tmap <M-e> <Esc>e
tmap <M-f> <Esc>f
tmap <M-g> <Esc>g
tmap <M-h> <Esc>h
tmap <M-i> <Esc>i
tmap <M-j> <Esc>j
tmap <M-k> <Esc>k
tmap <M-l> <Esc>l
tmap <M-m> <Esc>m
tmap <M-n> <Esc>n
tmap <M-o> <Esc>o
tmap <M-p> <Esc>p
tmap <M-q> <Esc>q
tmap <M-r> <Esc>r
tmap <M-s> <Esc>s
tmap <M-t> <Esc>t
tmap <M-u> <Esc>u
tmap <M-v> <Esc>v
tmap <M-w> <Esc>w
tmap <M-x> <Esc>x
tmap <M-y> <Esc>y
tmap <M-z> <Esc>z
tmap <M-{> <Esc>{
tmap <M-Bar> <Esc><Bar>
tmap <M-}> <Esc>}
tmap <M-~> <Esc>~
tmap <M-Del> <Esc><Del>
